### ISSUE TITLE
RenderOperatingSystem() returns wrong OS version on OCP 4.7.24

### ISSUE THREAD

**Issue by reenakabra** [openshift-psap/special-resource-operator#93]
OCP 4.7.24 uses rhel8.4 kernel. It is assumed that all OCP 4.7 versions will have rhel8.3. OS env variables are set incorrectly on OCP 4.7.24.

**Comment by itroyano** [comment]
Hi,

This is stated in Release Notes:

https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-rhcos-rhel-8-3-packages

`RHCOS now uses Red Hat Enterprise Linux (RHEL) 8.4 packages in OpenShift Container Platform 4.7.24 and above. This enables you to have the latest fixes, features, and enhancements, such as NetworkManager features, as well as the latest hardware support and driver updates. OpenShift Container Platform 4.6 is an Extended Update Support (EUS) release that will continue to use RHEL 8.2 EUS packages for the entirety of its lifecycle.`

Code line ref - 

https://github.com/openshift-psap/special-resource-operator/blob/ff01a1aaeb35847cf086a048cef062361053acf9/pkg/osversion/osversion.go#L20

**Comment by dagrayvid** [comment]
Hi @reenakabra. I believe this issue is actually unrelated to the RenderOperatingSystem() function (which should not be used anymore AFAIK). Instead SRO relies on the driver-toolkit image kernel versions. In version 4.7.24 the driver-toolkit has the incorrect kernel packages. This should be fixed in 4.7.25 and onwards.

**Comment by reenakabra** [comment]
Hi @dagrayvid. Is this fix available in 4.7.25, can we upgrade to that version? Will this be fixed on 4.7.24?

**Comment by dagrayvid** [comment]
Upgrading to 4.7.25 is my recommendation, as the driver-toolkit issue cannot be fixed on 4.7.24.

To clarify the issue, do you need the driver toolkit as a base image for the special resource you are deploying? If not, and the operator is still failing, then I need to investigate further.

**Comment by reenakabra** [comment]
@dagrayvid , will try upgrading to OCP4.7.25 or a later version and verify. Will get back to you in case of any issue. Thanks.

**Comment by apurv15** [comment]
We are seeing error with OCP 4.7.30 also. Can this be investigated?

**Comment by pacevedom** [comment]
The error you are seeing relates only to logs? I rigged a build to show versions from `dtk` and from `RenderOperatingSystem` and this is what I got:
```
2021-10-01T10:05:01.901Z	INFO	upgrade  	History	{"entry": "registry.ci.openshift.org/ocp/release@sha256:aba54b293dc151f5c0fd96d4353ced6ced3e7da6620c1c10714ab32d0577486f"}
2021-10-01T10:05:02.927Z	INFO	registry  	DTK	{"kernel-version": "4.18.0-305.19.1.el8_4.x86_64"}
2021-10-01T10:05:02.927Z	INFO	registry  	DTK	{"rt-kernel-version": "4.18.0-305.19.1.rt7.91.el8_4.x86_64"}
2021-10-01T10:05:02.927Z	INFO	registry  	DTK	{"rhel-version": "8.4"}
[...]
2021-10-01T10:05:04.957Z	INFO	ping-pong  	Runtime Information	{"Platform": "OCP"}
2021-10-01T10:05:04.957Z	INFO	ping-pong  	Runtime Information	{"ClusterVersion": "4.7.30"}
2021-10-01T10:05:04.957Z	INFO	ping-pong  	Runtime Information	{"ClusterVersionMajorMinor": "4.7"}
```

The `RenderOperatingSystem` function is only used for logging, apparently, and the one that counts is the version from `dtk`. Is the issue coming from a misleading log?

**Comment by reenakabra** [comment]
It is not logging issue. For infoscale driver container we are using SRO environment variables (Os version and kernel version). Due to incorrect os version pod bring up is stuck in image pull backoff state.

**Comment by pacevedom** [comment]
You are right, didnt check the templates. I will work on it.

**Comment by reenakabra** [comment]
Hi @dagrayvid @pacevedom, had couple of more concerns around this. From the fix done, if we are using RHEL_VERSION label do we still need change in RenderOperatingSystem() as OCP 4.7 supports both rhel8.3 and rhel8.4. This will fix installation problem on OCP 4.7.30 but upgrade will have issue.
In case of upgrade from 4.7.24 to 4.7.30 I think we still will have issues. ReconcileChartStates() will update RunInfo.OperatingSystemDecimal based on ClusterUpgradeInfo, it is not updating OperatingSystemMajor and OperatingSystemMajorMinor. For kernel affine driver container we make use of OperatingSystemMajorMinor that's why it is not getting updated info while trying to pull image.
In case of upgrade there will be 2 driver container daemonset on both OCP and K8s. In NodeVersionInfo() while creating the map, we are explicitly making use of label "feature.node.kubernetes.io/system-os_release.RHEL_VERSION", in K8s we will not be able to update the osversion based on this label.

Is this understanding correct. Please let me know if I am missing anything.
